connector:
  name: Prometheus
  identifier: prometheus
  description: Connector to Instruqt workshop Prometheus instance
  accountIdentifier: VEuU4vZ6QmSJZcgvnccqYQ
  orgIdentifier: default
  projectIdentifier: instruqt2
  type: Prometheus
  spec:
    url: http://prometheus-k8s.monitoring.svc.cluster.local:9090/
    delegateSelectors:
      - helm-delegate
    ignoreTestConnection: false
